#:import dp kivy.metrics.dp

<Button>:
    font_size: '17sp'
    color: 0.3, 0.6, 0.7, 1
    size_hint_y: None
    height: dp(50)


WindowManager:
    MainWindow:
    SecondWindow:
    ThirdWindow:
    FourthWindow:
    FifthWindow:


<MainWindow>:
    name: "Flight Plan"

    FloatLayout:

        canvas.before:
            Color:
                rgba: 0.3, 0.6, 0.7, 0.2
            RoundedRectangle:
                size: self.width, self.height * 0.20
                pos: self.x, self.y
                radius: [dp(40), dp(40), 0, 0]

        Image:
            source: 'ma60-f.jpg'
            size_hint: 0.70, 0.60
            pos_hint: {"x": 0.15, "y": 0.30}

        Label:
            text: "BEM VINDO AO SEU GESTOR DE VOO"
            font_name: "Roboto"
            font_size: '28sp'
            size_hint: 0.90, 0.10
            pos_hint:{"x": 0.05, "top": 0.96}
            halign: 'center'
            valign: 'middle'
            text_size: self.size

        GridLayout:
            cols: 4
            rows: 1
            spacing: dp(10)
            padding: dp(15)
            size_hint: 0.94, 0.14
            pos_hint:{"x": 0.03, "y": 0.05}

            Button:
                text: "Procurar"
                on_release:
                    app.root.current = "procurar"
                    root.manager.transition.direction = "left"

            Button:
                text: "Iniciar"
                on_release:
                    app.root.current = "voo"
                    root.manager.transition.direction = "left"

            Button:
                text: "Novo"
                on_release:
                    app.root.current = "New Plan"
                    root.manager.transition.direction = "left"

            Button:
                text: "Sair"
                on_release:
                    app.root.get_screen('Flight Plan').sair(root)


<SecondWindow>:
    name: "New Plan"

    partida: partida
    destino: destino
    mea: mea
    msa: msa
    nivelDeTransicao: nivelDeTransicao
    altitudeDeTransicao: altitudeDeTransicao
    radialRumo: radialRumo
    nivelDeVoo: nivelDeVoo
    aeronave: aeronave

    BoxLayout:
        orientation: 'vertical'
        padding: dp(15)
        spacing: dp(10)

        GridLayout:
            cols: 2
            rows: 9
            spacing: dp(8)
            size_hint_y: 0.78

            Label:
                text: "AD de partida"
                text_size: self.size

            TextInput:
                id: partida
                font_size: '20sp'
                multiline: False
                hint_text: "Ex.: fnlu"
                padding: dp(10), (self.height-self.line_height)/2 # alinha o hint text no meio do input

            Label:
                text: "AD de chegada"
                text_size: self.size

            TextInput:
                id: destino
                font_size: '20sp'
                multiline: False
                hint_text: "Ex.: fnmo"
                padding: dp(10), (self.height-self.line_height)/2

            Label:
                text: "Nível de voo"
                text_size: self.size

            TextInput:
                id: nivelDeVoo
                font_size: '20sp'
                multiline: False
                hint_text: "Ex.: 280"
                padding: dp(10), (self.height-self.line_height)/2

            Label:
                text: "Radial/Rumo"
                text_size: self.size

            TextInput:
                id: radialRumo
                font_size: '20sp'
                multiline: False
                hint_text: "Ex.: 270"
                padding: dp(10), (self.height-self.line_height)/2

            Label:
                text: "Alt. transição"
                text_size: self.size

            TextInput:
                id: altitudeDeTransicao
                font_size: '20sp'
                multiline: False
                hint_text: "Ex.: 10000"
                padding: dp(10), (self.height-self.line_height)/2

            Label:
                text: "Niv. transição"
                text_size: self.size

            TextInput:
                id: nivelDeTransicao
                font_size: '20sp'
                multiline: False
                hint_text: "Ex.: 120"
                padding: dp(10), (self.height-self.line_height)/2

            Label:
                text: "MEA"
                text_size: self.size

            TextInput:
                id: mea
                font_size: '20sp'
                multiline: False
                hint_text: "Ex.: 9000"
                padding: dp(10), (self.height-self.line_height)/2

            Label:
                text: "MSA"
                text_size: self.size

            TextInput:
                id: msa
                font_size: '20sp'
                multiline: False
                hint_text: "Ex.: 2500"
                padding: dp(10), (self.height-self.line_height)/2

            Label:
                text: "Aeronave"
                text_size: self.size

            TextInput:
                id: aeronave
                font_size: '20sp'
                multiline: False
                hint_text: "Ex.: T-270"
                padding: dp(10), (self.height-self.line_height)/2

        BoxLayout:
            spacing: dp(12)
            size_hint_y: 0.12

            Button:
                text: "Voltar"
                on_release:
                    app.root.current = "Flight Plan"
                    root.manager.transition.direction = "right"

            Button:
                text: "Avançar"
                on_release:
                    root.avancar()
                    app.root.current = "Waypoints"
                    root.manager.transition.direction = "left"


<ThirdWindow>:
    name: "Waypoints"

    wypt: wypt
    estima: estima
    lista: lista

    BoxLayout:
        orientation: 'vertical'
        padding: dp(15)
        spacing: dp(10)

        Label:
            text: "INSERIR WAYPOINT"
            font_size: '24sp'
            size_hint_y: 0.10
            halign: 'center'
            valign: 'middle'
            text_size: self.size

        GridLayout:
            cols: 3
            rows: 1
            spacing: dp(10)
            size_hint_y: 0.12

            Label:
                id: lista
                text: "Waypoint"
                size_hint_x: 0.20

            TextInput:
                id: wypt
                size_hint_x: 0.55
                font_size: '20sp'
                multiline: False
                hint_text: "Ex.: liram"
                padding: dp(10), (self.height-self.line_height)/2

            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(5)

                Label:
                    id: lista
                    text: "Tempo"
                    size_hint_x: 0.20

                TextInput:
                    id: estima
                    font_size: '20sp'
                    multiline: False
                    hint_text: "Ex.: 40"
                    padding: dp(10), (self.height-self.line_height)/2

                Button:
                    text: "+"
                    size_hint_x:  None
                    height: dp(32)
                    on_release:
                        root.add_waypoint()

        BoxLayout:
            size_hint_y: 0.60
            padding: dp(5)

            ScrollView:

                GridLayout:
                    id: box
                    cols: 1
                    orientation: 'lr-tb'
                    spacing: dp(8)
                    padding: dp(8)
                    size_hint_y: None
                    height: self.minimum_height

        BoxLayout:
            spacing: dp(12)
            spacing: dp(12)

            Button:
                text: "Voltar"
                on_release:
                    app.root.current = "New Plan"
                    root.manager.transition.direction = "right"

            Button:
                text: "Avançar"
                on_release:
                    root.avancar()
                    app.root.current = "voo"
                    root.manager.transition.direction = "left"


<FourthWindow>:
    name: "voo"

    # ==========================================================
    # OBJECT PROPERTIES
    # ==========================================================

    arranque: arranque
    descolagem: descolagem
    aterragem: aterragem
    corte: corte
    rota: rota
    min_enrout: min_enrout
    flt_level: flt_level
    min_sec: min_sec
    hdg: hdg
    alt_trans: alt_trans
    via: via
    niv_trans: niv_trans

    fltime: fltime
    blktime: blktime


    # ==========================================================
    # ECRÃ PRINCIPAL
    # ==========================================================

    FloatLayout:

        # ======================================================
        # ROTA
        # ======================================================

        Label:
            id: rota
            text: ''
            size_hint: 0.90, 0.08
            pos_hint:{"center_x": 0.62, "top": 0.94}
            font_size: '32sp'
            halign: 'center'
            valign: 'middle'
            text_size: self.size

        # ======================================================
        # COLUNA 1
        #
        # BOTÕES + HORAS
        # ======================================================

        BoxLayout:
            orientation: 'vertical'
            size_hint: 0.42, 0.55
            pos_hint:{"x": 0.03, "top": 0.86}
            spacing: '8dp'

            # --------------------------------------------------
            # START
            # --------------------------------------------------

            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: 0.25
                spacing: '8dp'

                Button:
                    id: arranque
                    text: "START"
                    size_hint_x: 0.58
                    on_release:
                        root.hora_start()

                BoxLayout:
                    id: box2
                    orientation: 'vertical'
                    size_hint_x: 0.42

            # --------------------------------------------------
            # DESCOLAGEM
            # --------------------------------------------------

            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: 0.25
                spacing: '8dp'

                Button:
                    id: descolagem
                    text: "DESCOLAGEM"
                    size_hint_x: 0.58
                    on_release:
                        root.hora_descolagem()

                BoxLayout:
                    id: box2_1
                    orientation: 'vertical'
                    size_hint_x: 0.42

            # --------------------------------------------------
            # ATERRAGEM
            # --------------------------------------------------

            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: 0.25
                spacing: '8dp'

                Button:
                    id: aterragem
                    text: "ATERRAGEM"
                    size_hint_x: 0.58
                    on_release:
                        root.hora_aterragem()

                BoxLayout:
                    id: box2_2
                    orientation: 'vertical'
                    size_hint_x: 0.42

            # --------------------------------------------------
            # CORTE
            # --------------------------------------------------

            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: 0.25
                spacing: '8dp'

                Button:
                    id: corte
                    text: "CORTE"
                    size_hint_x: 0.58
                    on_release:
                        root.hora_corte()

                BoxLayout:
                    id: box2_3
                    orientation: 'vertical'
                    size_hint_x: 0.42

        # ======================================================
        # COLUNA 2
        #
        # DADOS DO VOO
        #
        # HORA DE VOO FICA POR BAIXO
        # ======================================================

        BoxLayout:
            orientation: 'vertical'
            size_hint: 0.28, 0.55
            pos_hint:{"x": 0.40, "top": 0.86}
            spacing: '5dp'

            # --------------------------------------------------
            # DADOS DO VOO
            # --------------------------------------------------

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: 0.72
                spacing: '2dp'

                Label:
                    id: hdg
                    text: ''
                    font_size: '17sp'
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size

                Label:
                    id: flt_level
                    text: ''
                    font_size: '17sp'
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size

                Label:
                    id: min_enrout
                    text: ''
                    font_size: '17sp'
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size

                Label:
                    id: min_sec
                    text: ''
                    font_size: '17sp'
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size

                Label:
                    id: via
                    text: ''
                    font_size: '17sp'
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size

                Label:
                    id: alt_trans
                    text: ''
                    font_size: '17sp'
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size

                Label:
                    id: niv_trans
                    text: ''
                    font_size: '17sp'
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size

            # --------------------------------------------------
            # HORA DE VOO
            # --------------------------------------------------

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: 0.28
                spacing: '2dp'

                Label:
                    id: fltime
                    text: ''
                    size_hint_y: 0.60
                    font_size: '17sp'
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size

        # ======================================================
        # COLUNA 3
        #
        # ESTIMAS
        #
        # HORA BLOCO FICA POR BAIXO
        # ======================================================

        BoxLayout:
            orientation: 'vertical'
            size_hint: 0.22, 0.55
            pos_hint:{"x": 0.70, "top": 0.86}
            spacing: '5dp'

            # --------------------------------------------------
            # TÍTULO ESTIMAS
            # --------------------------------------------------

            Label:
                text: 'ESTIMAS'
                size_hint_y: 0.12
                font_size: '18sp'
                halign: 'center'
                valign: 'middle'
                text_size: self.size

            # --------------------------------------------------
            # SCROLLVIEW DAS ESTIMAS
            # --------------------------------------------------

            ScrollView:
                size_hint_y: 0.68
                do_scroll_x: False
                do_scroll_y: True
                bar_width: '6dp'

                GridLayout:
                    id: cx
                    cols: 1
                    spacing: '5dp'
                    padding: '5dp'
                    size_hint_y: None
                    height: self.minimum_height

            # --------------------------------------------------
            # HORA BLOCO
            # --------------------------------------------------

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: 0.32
                spacing: '2dp'

                Label:
                    id: blktime
                    text: ''
                    size_hint_y: 0.60
                    font_size: '17sp'
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size

        # ======================================================
        # BOTÕES INFERIORES
        # ======================================================

        BoxLayout:
            orientation: 'horizontal'
            size_hint: 0.42, 0.09
            pos_hint:{"x": 0.03, "y": 0.04}
            spacing: '12dp'

            Button:
                text: "INÍCIO"
                on_release:
                    app.root.current = "Flight Plan"
                    root.manager.transition.direction = "right"
                    root.ids.box2.clear_widgets()
                    root.ids.box2_1.clear_widgets()
                    root.ids.box2_2.clear_widgets()
                    root.ids.box2_3.clear_widgets()
                    root.ids.cx.clear_widgets()


            Button:
                text: "FECHAR"
                on_release:
                    app.root.get_screen('Flight Plan').sair(root)


<FifthWindow>:
    name: "procurar"

    posicao: posicao

    BoxLayout:
        orientation: 'vertical'
        padding: dp(15)
        spacing: dp(10)

        GridLayout:
            cols: 3
            rows: 1
            spacing: dp(10)
            size_hint_y: 0.12

            TextInput:
                id: posicao
                font_size: '18sp'
                multiline: False
                hint_text: "Ex.: fnlu, T-270"
                padding: dp(10), (self.height-self.line_height)/2

            Button:
                text: "Procurar"
                on_release:
                    root.ids.bx.clear_widgets(children=None)
                    root.procura_detalhada()

            Button:
                text: "Listar todos"
                on_release:
                    root.ids.bx.clear_widgets(children=None)
                    root.procurar_todos()

        BoxLayout:
            padding: dp(5)

            ScrollView:

                GridLayout:
                    id: bx
                    cols: 1
                    orientation: 'lr-tb'
                    spacing: dp(15)
                    padding: dp(5)
                    size_hint_y: None
                    height: self.minimum_height

        Button:
            text: "VOLTAR"
            size_hint_y: None
            height: dp(48)
            on_release:
                app.root.current = "Flight Plan"
                root.manager.transition.direction = "right"
                root.ids.bx.clear_widgets(children=None)


<Rota>:
    label: label
    eta: eta

    orientation: 'horizontal'
    size_hint_y: None
    height: dp(45)
    spacing: dp(5)
    padding: dp(5)

    Label:
        id: label
        font_size: '18sp'
        size_hint_x: 0.45
        halign: 'left'
        valign: 'middle'
        text_size: self.size

    Label:
        id: eta
        font_size: '18sp'
        size_hint_x: 0.40
        halign: 'center'
        valign: 'middle'
        text_size: self.size

    Button:
        text: "x"
        size_hint_x: None
        width: dp(50)
        on_release:
            app.root.get_screen('Waypoints').remover_waypoint(root)


<MostraProcura>:
    data: data
    aeronave: aeronave
    partida: partida
    chegada: chegada
    radial: radial
    nivel_v: nivel_v
    nivel_t: nivel_t
    alt_t: alt_t
    msa: msa
    mea: mea
    est: est
    id_voo: id_voo

    orientation: 'vertical'
    size_hint_y: None
    height: dp(80)
    padding: dp(8)

    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.2, 0.8
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(15)]

    BoxLayout:
        orientation: 'horizontal'
        spacing: dp(5)
        size_hint_y: 0.70

        Button:
            id: data
            text: root.data.text if root.data.text else ''
            font_size: '14sp'
            size_hint_x: 0.10
            background_color: 0,0,0,0
            color: 1,1,1,1
            on_release: root.editar_dados()

        Button:
            id: aeronave
            text: root.aeronave.text if root.aeronave.text else ''
            font_size: '14sp'
            size_hint_x: 0.10
            background_color: 0,0,0,0
            color: 1,1,1,1
            on_release: root.editar_dados()

        Button:
            id: partida
            text: root.partida.text if root.partida.text else ''
            font_size: '14sp'
            size_hint_x: 0.10
            background_color: 0,0,0,0
            color: 1,1,1,1
            on_release: root.editar_dados()

        Button:
            id: chegada
            text: root.chegada.text if root.chegada.text else ''
            font_size: '14sp'
            size_hint_x: 0.10
            background_color: 0,0,0,0
            color: 1,1,1,1
            on_release: root.editar_dados()

        Button:
            id: radial
            text: root.radial.text if root.radial.text else ''
            font_size: '14sp'
            size_hint_x: 0.10
            background_color: 0,0,0,0
            color: 1,1,1,1
            on_release: root.editar_dados()

        Button:
            id: nivel_v
            text: root.nivel_v.text if root.nivel_v.text else ''
            font_size: '14sp'
            size_hint_x: 0.10
            background_color: 0,0,0,0
            color: 1,1,1,1
            on_release: root.editar_dados()

        Button:
            id: nivel_t
            text: root.nivel_t.text if root.nivel_t.text else ''
            font_size: '14sp'
            size_hint_x: 0.10
            background_color: 0,0,0,0
            color: 1,1,1,1
            on_release: root.editar_dados()

        Button:
            id: alt_t
            text: root.alt_t.text if root.alt_t.text else ''
            font_size: '14sp'
            size_hint_x: 0.10
            background_color: 0,0,0,0
            color: 1,1,1,1
            on_release: root.editar_dados()

        Button:
            id: msa
            text: root.msa.text if root.msa.text else ''
            font_size: '14sp'
            size_hint_x: 0.10
            background_color: 0,0,0,0
            color: 1,1,1,1
            on_release: root.editar_dados()

        Button:
            id: mea
            text: root.mea.text if root.mea.text else ''
            font_size: '14sp'
            size_hint_x: 0.10
            background_color: 0,0,0,0
            color: 1,1,1,1
            on_release: root.editar_dados()

        Button:
            id: id_voo
            text: root.id_voo.text if root.id_voo.text else ''
            opacity: 0
            size_hint_x: 0.01

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.30
        spacing: dp(5)

        Button:
            id: est
            text: root.est.text if root.est.text else ''
            font_size: '14sp'
            background_color: 0,0,0,0
            color: 1,1,1,1
            on_release: root.editar_dados()


<ListaProcura>:
    data: data
    acft: acft
    dep: dep
    arr: arr
    fl: fl
    rad: rad
    alt_trans: alt_trans
    niv_trans: niv_trans
    min_enrout: min_enrout
    min_safe: min_safe
    estimas: estimas

    orientation: 'vertical'
    size_hint_y: None
    height: dp(50)
    padding: dp(8)

    canvas.before:
        Color:
            rgba: 0, 0.9, 0, 0.6
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(15)]

    BoxLayout:
        orientation: 'horizontal'
        spacing: dp(5)
        size_hint_y: 0.70

        Label:
            id: data
            font_size: '14sp'
            size_hint_x: 0.10
            bold: True
            halign: 'center'
            text_size: self.size

        Label:
            id: acft
            font_size: '14sp'
            size_hint_x: 0.10
            bold: True
            halign: 'center'
            text_size: self.size

        Label:
            id: dep
            font_size: '14sp'
            size_hint_x: 0.10
            bold: True
            halign: 'center'
            text_size: self.size

        Label:
            id: arr
            font_size: '14sp'
            size_hint_x: 0.10
            bold: True
            halign: 'center'
            text_size: self.size

        Label:
            id: fl
            font_size: '14sp'
            size_hint_x: 0.10
            bold: True
            halign: 'center'
            text_size: self.size

        Label:
            id: rad
            font_size: '14sp'
            size_hint_x: 0.10
            bold: True
            halign: 'center'
            text_size: self.size

        Label:
            id: alt_trans
            font_size: '14sp'
            size_hint_x: 0.10
            bold: True
            halign: 'center'
            text_size: self.size

        Label:
            id: niv_trans
            font_size: '14sp'
            size_hint_x: 0.10
            bold: True
            halign: 'center'
            text_size: self.size

        Label:
            id: min_enrout
            font_size: '14sp'
            size_hint_x: 0.10
            bold: True
            halign: 'center'
            text_size: self.size

        Label:
            id: min_safe
            font_size: '14sp'
            size_hint_x: 0.10
            bold: True
            halign: 'center'
            text_size: self.size

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.30

        Label:
            id: estimas
            font_size: '14sp'
            bold: True
            halign: 'center'
            valign: 'middle'
            text_size: self.size


<Pontos>:
    pto: pto
    temp: temp

    orientation: 'horizontal'
    size_hint_y: None
    height: dp(35)
    spacing: dp(5)

    Label:
        id: pto
        font_size: '18sp'
        size_hint_x: 0.60
        halign: 'left'
        valign: 'middle'
        text_size: self.size

    Label:
        id: temp
        font_size: '18sp'
        size_hint_x: 0.40
        halign: 'center'
        valign: 'middle'
        text_size: self.size


<Relogio>:
    cronometro: cronometro

    cols: 1
    size_hint_y: None
    height: '35dp'

    Label:
        id: cronometro
        font_size: '18sp'
        halign: 'left'
        valign: 'middle'
        text_size: self.size