name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Linux packages
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev \
            libncursesw5-dev libtinfo6 cmake \
            libffi-dev libssl-dev build-essential libstdc++6 aidl curl

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install cython buildozer

      - name: Pre-download Android SDK and Accept Licenses
        run: |
          # 1. Criar a estrutura correta de diretórios que o Buildozer espera
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          
          # 2. Descarregar os binários originais do sdkmanager da Google (ferramenta legado esperada pelo Buildozer)
          curl -L -o sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          unzip -q sdk-tools.zip -d ~/.buildozer/android/platform/android-sdk/
          rm sdk-tools.zip

          # 3. Injetar os hashes das licenças na pasta que acabámos de popular
          echo -e "\n8933bad161d74778b1f5b0028a1265521346616e\nd56f5187479451eabf01fb743130245313541d83\n24333f1a63b6825ea9c5514f83c2829b004d1fee" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GestorDeVoo-APK
          path: bin/*.apk
